name: FirstTouch

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"

configs:
  Debug: debug
  Release: release

targets:
  FirstTouch:
    type: application
    platform: iOS

    sources:
      - path: Sources/FirstTouch

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.FirstTouch
        SWIFT_VERSION: 5.0

        # 🔑 Explicit Info.plist (fixes CI archive validation)
        INFOPLIST_FILE: Sources/FirstTouch/Info.plist

        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1

        # Unsigned build (eSign-compatible)
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""

    scheme:
      build:
        targets:
          FirstTouch: all
