name: FirstTouch

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"

configs:
  Debug: debug
  Release: release

targets:
  FirstTouch:
    type: application
    platform: iOS

    sources:
      - path: Sources/FirstTouch

    settings:
      base:
        # Identity
        PRODUCT_BUNDLE_IDENTIFIER: com.example.FirstTouch
        SWIFT_VERSION: 5.0

        # ❗ Required for CI + unsigned archive
        GENERATE_INFOPLIST_FILE: YES

        # Info.plist contents (generated at build time)
        INFOPLIST_KEY_CFBundleDisplayName: FirstTouch
        INFOPLIST_KEY_CFBundleShortVersionString: 1.0.0
        INFOPLIST_KEY_CFBundleVersion: 1

        # SwiftUI app requirements
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES

        # Device requirements
        INFOPLIST_KEY_UIRequiredDeviceCapabilities: arm64

        # Signing (disabled — eSign will sign later)
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""

    scheme:
      build:
        targets:
          FirstTouch: all
